package com.tenutz.cracknotifier.domain.robot;

import com.tenutz.cracknotifier.domain.base.BaseTimeEntity;
import com.tenutz.cracknotifier.domain.user.User;
import com.tenutz.cracknotifier.util.manager.SeqManager;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Collections;

@DynamicInsert
@DynamicUpdate
@Entity
@Getter
@Setter(value = AccessLevel.PROTECTED)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table
public class Robot extends BaseTimeEntity {

    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "seq_manager_rbot")
    @GenericGenerator(name = "seq_manager_rbot", strategy = "com.tenutz.cracknotifier.util.manager.SeqManager", parameters = {
            @org.hibernate.annotations.Parameter(name = SeqManager.INCREMENT_PARAM, value = "1"),
            @org.hibernate.annotations.Parameter(name = SeqManager.VALUE_USER_SEQ_PARAMETER, value = "rbot_"),
            @org.hibernate.annotations.Parameter(name = SeqManager.NUMBER_FORMAT_PARAMETER, value = "%010d"),
            @org.hibernate.annotations.Parameter(name = SeqManager.VALUE_COLUMN_PARAM, value = "seq")
    })
    @Column(nullable = false, updatable = false, length = 15)
    @Id
    private String seq;

    @Column(nullable = false, updatable = false, unique = true, length = 30)
    private String modelNo;

    @Column
    private String image;

    @Column(nullable = false, columnDefinition = "float(11, 4) default 0.0000")
    private float width;

    @Column(nullable = false, columnDefinition = "float(11, 4) default 0.0000")
    private float depth;

    @Column(nullable = false, columnDefinition = "float(11, 4) default 0.0000")
    private float height;

    @Column(nullable = false, columnDefinition = "float(11, 4) default 0.0000")
    private float weight;

    @Column(columnDefinition = "tinyint(1) default 0")
    private boolean batteryNotified;

    public static Robot create(String modelNoAutoGenerated, float width, float depth, float height, float weight) {
        Robot robot = new Robot();
        robot.setModelNo(modelNoAutoGenerated);
        robot.setWidth(width);
        robot.setDepth(depth);
        robot.setHeight(height);
        robot.setWeight(weight);
        return robot;
    }

    public void notifyBattery() {
        setBatteryNotified(true);
    }

    public void resetBatteryNotification() {
        setBatteryNotified(false);
    }
}
